name: 'Falco Action'
description: 'Run Falco in a GitHub action'
author: 'The Falco Authors'
inputs:
  config_file:
    description: 'Start action with a config file'
    required: false
    default: 'src/ignore.config'
  verbose:
    description: 'Enable verbose logs'
    type: boolean
    default: false
runs:
  using: 'composite'
  steps:
  - name: Start Sysdig capture
    shell: bash
    run: |
      IGNORE_FILTER_FOLDER=${{github.action_path}}/src
      CONFIG_FILE="${{github.action_path}}/${{inputs.config_file}}"

      if [ ! -e "$CONFIG_FILE" ]; then
        echo "Config File does not exist."
        echo $CONFIG_FILE
        exit 1
      fi

      if [[ "${{ inputs.verbose }}" == "true" ]]; then
        echo "Config File:"
        cat $CONFIG_FILE
      fi

      echo "Creating ignore filters"
      IGNORE_IPS_FILTER="and not fd.sip in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_ips.jq $CONFIG_FILE) ) "
      IGNORE_FOLDERS_FILTER="and not fd.directory in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_folders.jq $CONFIG_FILE) ) "
      IGNORE_FILES_FILTER="and not fd.name in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_files.jq $CONFIG_FILE) ) "
      IGNORE_SYSCALLS_FILTER="and not evt.type in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_syscalls.jq $CONFIG_FILE) ) "
      IGNORE_PROCESSES_FILTER="and not proc.name in ( $(jq -r  -f $IGNORE_FILTER_FOLDER/ignore_processes.jq $CONFIG_FILE) ) "


      if [[ "${{ inputs.verbose }}" == "true" ]]; then
        echo "Ignored IPs:"
        echo $IGNORE_IPS_FILTER

        echo "Ignored Folders:"
        echo $IGNORE_FOLDERS_FILTER

        echo "Ignored Files:"
        echo $IGNORE_FILES_FILTER

        echo "Ignored Syscalls:"
        echo $IGNORE_SYSCALLS_FILTER

        echo "Ignored Processes:"
        echo $IGNORE_PROCESSES_FILTER
      fi

      echo "Creating Sysdig container"
      docker run --rm -d --name sysdig --privileged \
      -v /var/run/docker.sock:/host/var/run/docker.sock \
      -v /dev:/host/dev -v /proc:/host/proc:ro \
      -v /boot:/host/boot:ro \
      -v /lib/modules:/host/lib/modules:ro \
      -v /usr:/host/usr:ro \
      -v /tmp:/tmp \
      --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/capture.scap --snaplen=256 "not evt.type in (switch) $IGNORE_SYSCALLS_FILTER $IGNORE_PROCESSES_FILTER $IGNORE_FOLDERS_FILTER $IGNORE_FILES_FILTER"
      echo "Sysdig started"

      # Ensure Sysdig container is running
      sleep 10 # todo(loresuso): replace with a more robust check

      if [[ "${{ inputs.verbose }}" == "true" ]]; then
        docker ps -a
        docker logs sysdig
      fi