name: 'Falco Action'
description: 'Run Falco in a GitHub action'
author: 'The Falco Authors'
inputs:
  config_file:
    description: 'start action config file'
    required: false
    default: 'start/src/ignore.config'
runs:
  using: 'composite'
  steps:
  - name: Start Sysdig capture
    shell: bash
    run: |
      IGNORE_FILTER_FOLDER=${{github.action_path}}/start/src
      CONFIG_FILE="${{github.action_path}}/${{inputs.config_file}}"

      if [ ! -e "$CONFIG_FILE" ]; then
        echo "Config File does not exist."
        exit 1
      fi

      echo "Creating ignore filters"

      echo "Ignored IPs:"
      IGNORE_IPS_FILTER="and not fd.sip in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_ips.jq $CONFIG_FILE) ) "
      echo $IGNORE_IPS_FILTER

      echo "Ignored Folders:"
      IGNORE_FOLDERS_FILTER="and not fd.directory in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_folders.jq $CONFIG_FILE) ) "
      echo $IGNORE_FOLDERS_FILTER

      echo "Ignored Files:"
      IGNORE_FILES_FILTER="and not fd.name in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_files.jq $CONFIG_FILE) ) "
      echo $IGNORE_FILES_FILTER

      echo "Ignored Syscalls:"
      IGNORE_SYSCALLS_FILTER="and not evt.type in ( $(jq -r -f $IGNORE_FILTER_FOLDER/ignore_syscalls.jq $CONFIG_FILE) ) "
      echo $IGNORE_SYSCALLS_FILTER

      echo "Ignored Processes:"
      IGNORE_PROCESSES_FILTER="and not proc.name in ( $(jq -r  -f $IGNORE_FILTER_FOLDER/ignore_processes.jq $CONFIG_FILE) ) "
      echo $IGNORE_PROCESSES_FILTER

      echo "Creating Sysdig container"
      docker run --rm -d --name sysdig --privileged \
      -v /var/run/docker.sock:/host/var/run/docker.sock \
      -v /dev:/host/dev -v /proc:/host/proc:ro \
      -v /boot:/host/boot:ro \
      -v /lib/modules:/host/lib/modules:ro \
      -v /usr:/host/usr:ro \
      -v /tmp:/tmp \
      --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/capture.scap --snaplen=256 "not evt.type in (switch) $IGNORE_SYSCALLS_FILTER $IGNORE_PROCESSES_FILTER $IGNORE_FOLDERS_FILTER $IGNORE_FILES_FILTER"
      echo "Sysdig started"

      # Ensure Sysdig container is running
      sleep 10 # todo(loresuso): replace with a more robust check
      docker ps -a 
      docker logs sysdig