on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@9e046442f25193054d3a72378c293e60e0f80e72
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt

    - name: Stop Falco
      uses: darryk10/falco-action/stop@9e046442f25193054d3a72378c293e60e0f80e72
      with:
        mode: live
        verbose: true
