on:
  workflow_dispatch:

name: Test Live Mode

jobs:
  test-falco-live:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@80e3c126abe2d9ffa07525447f020ccf7faed4a1
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
    
    - name: Privileged container
      run: |
        sleep 1
        docker run --rm -d --privileged hello-world
        sleep 1

    - name: Stop Falco
      uses: darryk10/falco-action/stop@80e3c126abe2d9ffa07525447f020ccf7faed4a1
      with:
        mode: live
        verbose: true