on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@9900013f534c1e9d956d1ff19d4db7682044bc9f
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt

    - name: Stop Falco
      uses: darryk10/falco-action/stop@9900013f534c1e9d956d1ff19d4db7682044bc9f
      with:
        mode: live
        verbose: true
