on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@38f697dfb62c8a3a9cb78e9e5e149c37a1caa6f3
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
    
    - name: Privileged container
      run: |
        sleep 1
        docker run --rm -d --privileged hello-world
        sleep 1

    - name: Stop Falco
      uses: darryk10/falco-action/stop@38f697dfb62c8a3a9cb78e9e5e149c37a1caa6f3
      with:
        mode: live
        verbose: true
