on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@4b4407d619fa5500ffe7c4a0ba76229c2aa72936
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt

    - name: Stop Falco
      uses: darryk10/falco-action/stop@4b4407d619fa5500ffe7c4a0ba76229c2aa72936
      with:
        mode: live
        verbose: true
