on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@a2caced8ca0b63ed5a3d6dae8f602a78b64a6d6a
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt

    - name: Stop Falco
      uses: darryk10/falco-action/stop@a2caced8ca0b63ed5a3d6dae8f602a78b64a6d6a
      with:
        mode: live
        verbose: true
