on:
  workflow_dispatch:

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@621cc2364f0e21aa2c9d66345e09617f802067df
      with:
        mode: live
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt

    - name: Stop Falco
      uses: darryk10/falco-action/stop@621cc2364f0e21aa2c9d66345e09617f802067df
      with:
        mode: live
        verbose: true
