on:
  workflow_dispatch:

name: Test Analyze Mode

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@5760dd3ae7a1edb7da3b00d53f17154fc85b1f16
      with:
        mode: analyze
        falco-version: '0.29.0'
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
    
    - name: Privileged container
      run: |
        sleep 1
        docker run --rm -d --privileged hello-world
        sleep 1

    - name: Stop Falco
      uses: darryk10/falco-action/stop@5760dd3ae7a1edb7da3b00d53f17154fc85b1f16
      with:
        mode: analyze
        verbose: true

  analyze:
    runs-on: ubuntu-latest
    needs: test-falco
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: darryk10/falco-action/analyze@5760dd3ae7a1edb7da3b00d53f17154fc85b1f16