on:
  workflow_dispatch:

name: Test Analyze Mode

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start Falco
      uses: darryk10/falco-action/start@3e3ec1727005bf3a844460a878c792a0b192b2ae
      with:
        mode: analyze
        verbose: true

    - name: Overwrite Source Code
      shell: bash
      run: |
        echo "pwned" > ${{ github.workspace }}/pwn.txt
    
    - name: Privileged container
      run: |
        sleep 1
        docker run --rm -d --privileged hello-world
        sleep 1

    - name: Stop Falco
      uses: darryk10/falco-action/stop@3e3ec1727005bf3a844460a878c792a0b192b2ae
      with:
        mode: analyze
        verbose: true

  analyze:
    runs-on: ubuntu-latest
    needs: test-falco
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: darryk10/falco-action/analyze@3e3ec1727005bf3a844460a878c792a0b192b2ae
      with:
        falco-version: '0.39.0'